#!/bin/bash
# Auto-generated by submitjob.py

#PBS -l walltime=0:30:00         # 30-minute limit
#PBS -l nodes=1:ppn=24           # single 24-core node

cd "$PBS_O_WORKDIR"

# Run program; summary will appear in benchmark-2294.out
mpirun -np 24 ./wsp-mpi ./input/dist18
